In [1]:
%%capture
!pip install duckdb
!pip install ipython-sql
!pip install SQLAlchemy
!pip install duckdb-engine

#Drive mount

In [11]:
# Load the Drive helper and mount
from google.colab import drive
drive.mount('/content/drive/', force_remount=True)

Mounted at /content/drive/

#Import & Setup

In [3]:
import duckdb
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sqlalchemy
from datetime import datetime as dt
import glob

# Import ipython-sql Jupyter extension to create SQL cells
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: UserWarning: Config option `displaycon` not recognized by `SqlMagic`.  Did you mean `displaylimit`?
  exec(code_obj, self.user_global_ns, self.user_ns)

In [15]:
# %sql duckdb:////content/drive/MyDrive/ADSDBProject/formatted/crimesPrices.db
# to use a database file (shared between processes)
mostRecent = glob.glob("/content/drive/MyDrive/ADSDB/ADSDB Project/trusted/*.db")[-1]
con = duckdb.connect(database=mostRecent)

Import tables

In [26]:
crimes = con.execute("SELECT * FROM crimes").df()
prices = con.execute("SELECT * FROM prices").df()

#Delete columns

In [27]:
crimes

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,NaN,2020-06,Lincolnshire Police,Lincolnshire Police,-0.775772,53.266281,On or near Marsh Lane,E01028039,Bassetlaw 015F,Anti-social behaviour,NaN,NaN
1,NaN,2020-06,Lincolnshire Police,Lincolnshire Police,0.065595,52.983426,On or near Church Road,E01026007,Boston 001A,Anti-social behaviour,NaN,NaN
2,NaN,2020-06,Lincolnshire Police,Lincolnshire Police,0.065595,52.983426,On or near Church Road,E01026007,Boston 001A,Anti-social behaviour,NaN,NaN
3,NaN,2020-06,Lincolnshire Police,Lincolnshire Police,0.065595,52.983426,On or near Church Road,E01026007,Boston 001A,Anti-social behaviour,NaN,NaN
4,NaN,2020-06,Lincolnshire Police,Lincolnshire Police,0.065595,52.983426,On or near Church Road,E01026007,Boston 001A,Anti-social behaviour,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
78999,NaN,2021-02,Lincolnshire Police,Lincolnshire Police,-0.538147,53.223655,On or near Lewis Street,E01026176,Lincoln 006B,Anti-social behaviour,NaN,NaN
79000,NaN,2021-02,Lincolnshire Police,Lincolnshire Police,-0.540080,53.226735,On or near St Mary'S Street,E01026176,Lincoln 006B,Anti-social behaviour,NaN,NaN
79001,NaN,2021-02,Lincolnshire Police,Lincolnshire Police,-0.539346,53.223642,On or near Portland Street,E01026176,Lincoln 006B,Anti-social behaviour,NaN,NaN
79002,4c7c59ac8f79034a6cb6abd3612aafd85e2a0e058b2113...,2021-02,Lincolnshire Police,Lincolnshire Police,-0.531439,53.222260,On or near Elliott Road,E01026176,Lincoln 006B,Bicycle theft,Investigation complete; no suspect identified,NaN
79003,9b36fe02ff1aa4f986c6fc38302ee20139e44378812b1f...,2021-02,Lincolnshire Police,Lincolnshire Police,-0.541377,53.222939,On or near Hermit Street,E01026176,Lincoln 006B,Criminal damage and arson,Court result unavailable,NaN

In [28]:
prices

,OrganisationLabel,OrganisationURI,PublishedDate,LatestData,DurationFrom,DurationTo,ReportingPeriodType,Month,GeoEntityName,GeoCode,GeoName,GeoURI,AveragePrice,AveragePriceDetached,AveragePriceSemiDetached,AveragePriceTerraced,AveragePriceFlatOrMaisonette
0,Lincolnshire,http://opendatacommunities.org/id/county-counc...,2022-08-19,NaN,2022-04-01,2022-04-30 23:59:59,Month,2022-04,County,E10000019,Lincolnshire,http://statistics.data.gov.uk/doc/statistical-...,227107,302732,201578,160623,109834
1,Lincolnshire,http://opendatacommunities.org/id/county-counc...,2022-08-19,NaN,2022-04-01,2022-04-30 23:59:59,Month,2022-04,District Council,E07000136,Boston,http://statistics.data.gov.uk/doc/statistical-...,196216,271072,169355,134146,94306
2,Lincolnshire,http://opendatacommunities.org/id/county-counc...,2022-08-19,NaN,2022-04-01,2022-04-30 23:59:59,Month,2022-04,District Council,E07000137,East Lindsey,http://statistics.data.gov.uk/doc/statistical-...,218193,272378,185271,145679,99663
3,Lincolnshire,http://opendatacommunities.org/id/county-counc...,2022-08-19,NaN,2022-04-01,2022-04-30 23:59:59,Month,2022-04,District Council,E07000138,Lincoln,http://statistics.data.gov.uk/doc/statistical-...,182188,296222,198998,151938,113243
4,Lincolnshire,http://opendatacommunities.org/id/county-counc...,2022-08-19,NaN,2022-04-01,2022-04-30 23:59:59,Month,2022-04,District Council,E07000139,North Kesteven,http://statistics.data.gov.uk/doc/statistical-...,254537,311139,210277,171161,110274
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,Lincolnshire,http://opendatacommunities.org/id/county-counc...,2022-08-19,NaN,2021-06-01,2021-06-30 23:59:59,Month,2021-06,District Council,E07000138,Lincoln,http://statistics.data.gov.uk/doc/statistical-...,172907,278217,187155,144950,111264
84,Lincolnshire,http://opendatacommunities.org/id/county-counc...,2022-08-19,NaN,2021-06-01,2021-06-30 23:59:59,Month,2021-06,District Council,E07000139,North Kesteven,http://statistics.data.gov.uk/doc/statistical-...,232762,282779,191790,159253,106618
85,Lincolnshire,http://opendatacommunities.org/id/county-counc...,2022-08-19,NaN,2021-06-01,2021-06-30 23:59:59,Month,2021-06,District Council,E07000140,South Holland,http://statistics.data.gov.uk/doc/statistical-...,207140,257482,175744,143657,88720
86,Lincolnshire,http://opendatacommunities.org/id/county-counc...,2022-08-19,NaN,2021-06-01,2021-06-30 23:59:59,Month,2021-06,District Council,E07000141,South Kesteven,http://statistics.data.gov.uk/doc/statistical-...,233210,329112,210996,171360,113540
87,Lincolnshire,http://opendatacommunities.org/id/county-counc...,2022-08-19,NaN,2021-06-01,2021-06-30 23:59:59,Month,2021-06,District Council,E07000142,West Lindsey,http://statistics.data.gov.uk/doc/statistical-...,193552,255792,164914,134390,99424

In [29]:
prices = prices.drop(['LatestData', 'DurationFrom', 'DurationTo', 'GeoURI', 'OrganisationURI', 'GeoCode', 'PublishedDate'], axis=1)

In [32]:
crimes = crimes.drop(['LSOA code', 'Crime ID', 'Context'], axis=1)